// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"errors"
	"fmt"
)

const (
	// AuthProviderGoogle is a AuthProvider of type google.
	AuthProviderGoogle AuthProvider = "google"
	// AuthProviderFacebook is a AuthProvider of type facebook.
	AuthProviderFacebook AuthProvider = "facebook"
	// AuthProviderApple is a AuthProvider of type apple.
	AuthProviderApple AuthProvider = "apple"
)

var ErrInvalidAuthProvider = errors.New("not a valid AuthProvider")

// String implements the Stringer interface.
func (x AuthProvider) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AuthProvider) IsValid() bool {
	_, err := ParseAuthProvider(string(x))
	return err == nil
}

var _AuthProviderValue = map[string]AuthProvider{
	"google":   AuthProviderGoogle,
	"facebook": AuthProviderFacebook,
	"apple":    AuthProviderApple,
}

// ParseAuthProvider attempts to convert a string to a AuthProvider.
func ParseAuthProvider(name string) (AuthProvider, error) {
	if x, ok := _AuthProviderValue[name]; ok {
		return x, nil
	}
	return AuthProvider(""), fmt.Errorf("%s is %w", name, ErrInvalidAuthProvider)
}

// MarshalText implements the text marshaller method.
func (x AuthProvider) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *AuthProvider) UnmarshalText(text []byte) error {
	tmp, err := ParseAuthProvider(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
