// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	interfaces "gitlab.com/jideobs/nebularcore/modules/auth/interfaces"

	requests "gitlab.com/jideobs/nebularcore/modules/auth/models/requests"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: ctx, user, payload
func (_m *Manager) ChangePassword(ctx context.Context, user interfaces.User, payload requests.PasswordChangePayload) error {
	ret := _m.Called(ctx, user, payload)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.User, requests.PasswordChangePayload) error); ok {
		r0 = rf(ctx, user, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestPasswordReset provides a mock function with given fields: ctx, payload
func (_m *Manager) RequestPasswordReset(ctx context.Context, payload requests.PasswordResetPayload) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, requests.PasswordResetPayload) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyPasswordReset provides a mock function with given fields: ctx, payload
func (_m *Manager) VerifyPasswordReset(ctx context.Context, payload requests.PasswordResetVerifyPayload) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, requests.PasswordResetVerifyPayload) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
