#!/bin/bash

set -e


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $DATABASE_USERNAME WITH PASSWORD '$DATABASE_PASSWORD';
	CREATE DATABASE $DATABASE_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USERNAME;
	GRANT ALL PRIVILEGES ON SCHEMA public TO $DATABASE_USERNAME;
	ALTER SCHEMA public OWNER TO $DATABASE_USERNAME;
	ALTER DATABASE $DATABASE_NAME SET timezone TO 'UTC';
	ALTER DATABASE $DATABASE_NAME OWNER TO $DATABASE_USERNAME;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DATABASE_NAME" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL
