// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	backends "github.com/volvlabs/nebularcore/modules/auth/backends"

	interfaces "github.com/volvlabs/nebularcore/modules/auth/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// AuthenticationManager is an autogenerated mock type for the AuthenticationManager type
type AuthenticationManager struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: ctx, credentials
func (_m *AuthenticationManager) Authenticate(ctx context.Context, credentials map[string]interface{}) (interfaces.User, error) {
	ret := _m.Called(ctx, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 interfaces.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) (interfaces.User, error)); ok {
		return rf(ctx, credentials)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) interfaces.User); ok {
		r0 = rf(ctx, credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterBackend provides a mock function with given fields: name, backend
func (_m *AuthenticationManager) RegisterBackend(name string, backend backends.AuthenticationBackend) {
	_m.Called(name, backend)
}

// ValidateToken provides a mock function with given fields: ctx, token
func (_m *AuthenticationManager) ValidateToken(ctx context.Context, token string) (interfaces.User, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 interfaces.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (interfaces.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interfaces.User); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthenticationManager creates a new instance of AuthenticationManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticationManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticationManager {
	mock := &AuthenticationManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
