// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	interfaces "gitlab.com/jideobs/nebularcore/modules/auth/interfaces"
)

// AuthenticationBackend is an autogenerated mock type for the AuthenticationBackend type
type AuthenticationBackend struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: ctx, credentials
func (_m *AuthenticationBackend) Authenticate(ctx context.Context, credentials map[string]interface{}) (interfaces.User, error) {
	ret := _m.Called(ctx, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 interfaces.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) (interfaces.User, error)); ok {
		return rf(ctx, credentials)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) interfaces.User); ok {
		r0 = rf(ctx, credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}) error); ok {
		r1 = rf(ctx, credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateToken provides a mock function with given fields: ctx, token
func (_m *AuthenticationBackend) ValidateToken(ctx context.Context, token string) (interfaces.User, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 interfaces.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (interfaces.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interfaces.User); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthenticationBackend creates a new instance of AuthenticationBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticationBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticationBackend {
	mock := &AuthenticationBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
