core:
  environment: development
  database:
    driver: postgres
    host: localhost
    username: postgres
    password: password
    name: nebularcore
    port: "5432"
    sslmode: disable
  server:
    port: "8888"
    host: localhost
    shutdownTimeout: 5s
    allowedOrigins: "*"
modules:
  auth:
    userMigrationScriptPath: "./migrations"
    backends:
      - local
    jwt:
      accessTokenSecret: this-is-a-sample-secret
      refreshTokenSecret: this-is-a-sample-secret
      accessTokenExpiry: 24h
      refreshTokenExpiry: 720h
    passwordPolicy:
      minLength: 8
      requireUpper: true
      requireLower: true
      requireNumber: true
      requireSpecial: true
    apiKey:
      length: 32
      expiryTime: 8760h
      rateLimit:
        enabled: true
        requests: 1000
        period: 1h
    social:
      enabled: false
    clerk:
      apiKey: ""
      apiEndpoint: ""
      frontendAPI: ""
