// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	event "github.com/volvlabs/nebularcore/modules/event"
)

// EventBus is an autogenerated mock type for the EventBus type
type EventBus struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, _a1
func (_m *EventBus) Publish(ctx context.Context, _a1 event.Message) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.Message) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishAsync provides a mock function with given fields: ctx, _a1
func (_m *EventBus) PublishAsync(ctx context.Context, _a1 event.Message) (<-chan error, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PublishAsync")
	}

	var r0 <-chan error
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, event.Message) (<-chan error, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, event.Message) <-chan error); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, event.Message) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscribe provides a mock function with given fields: eventType, handler
func (_m *EventBus) Subscribe(eventType string, handler event.Handler) error {
	ret := _m.Called(eventType, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, event.Handler) error); ok {
		r0 = rf(eventType, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Unsubscribe provides a mock function with given fields: eventType
func (_m *EventBus) Unsubscribe(eventType string) error {
	ret := _m.Called(eventType)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(eventType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventBus creates a new instance of EventBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventBus {
	mock := &EventBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
