// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	emitter "gitlab.com/jideobs/nebularcore/modules/auth/emitter"
	interfaces "gitlab.com/jideobs/nebularcore/modules/auth/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// EventEmitter is an autogenerated mock type for the EventEmitter type
type EventEmitter struct {
	mock.Mock
}

// EmitAuthEvent provides a mock function with given fields: ctx, user, data
func (_m *EventEmitter) EmitAuthEvent(ctx context.Context, user interfaces.User, data emitter.AuthEventData) error {
	ret := _m.Called(ctx, user, data)

	if len(ret) == 0 {
		panic("no return value specified for EmitAuthEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.User, emitter.AuthEventData) error); ok {
		r0 = rf(ctx, user, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitLoginEvent provides a mock function with given fields: ctx, user, ip, userAgent, success
func (_m *EventEmitter) EmitLoginEvent(ctx context.Context, user interfaces.User, ip string, userAgent string, success bool) error {
	ret := _m.Called(ctx, user, ip, userAgent, success)

	if len(ret) == 0 {
		panic("no return value specified for EmitLoginEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.User, string, string, bool) error); ok {
		r0 = rf(ctx, user, ip, userAgent, success)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitPasswordChangedEvent provides a mock function with given fields: ctx, user
func (_m *EventEmitter) EmitPasswordChangedEvent(ctx context.Context, user interfaces.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for EmitPasswordChangedEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitPasswordEvent provides a mock function with given fields: ctx, user, ip, userAgent, eventType
func (_m *EventEmitter) EmitPasswordEvent(ctx context.Context, user interfaces.User, ip string, userAgent string, eventType string) error {
	ret := _m.Called(ctx, user, ip, userAgent, eventType)

	if len(ret) == 0 {
		panic("no return value specified for EmitPasswordEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.User, string, string, string) error); ok {
		r0 = rf(ctx, user, ip, userAgent, eventType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitPasswordResetEvent provides a mock function with given fields: ctx, user
func (_m *EventEmitter) EmitPasswordResetEvent(ctx context.Context, user interfaces.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for EmitPasswordResetEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitPasswordResetInitiatedEvent provides a mock function with given fields: ctx, user, resetToken
func (_m *EventEmitter) EmitPasswordResetInitiatedEvent(ctx context.Context, user interfaces.User, resetToken string) error {
	ret := _m.Called(ctx, user, resetToken)

	if len(ret) == 0 {
		panic("no return value specified for EmitPasswordResetInitiatedEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.User, string) error); ok {
		r0 = rf(ctx, user, resetToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmitUserEvent provides a mock function with given fields: ctx, user, eventType
func (_m *EventEmitter) EmitUserEvent(ctx context.Context, user interfaces.User, eventType string) error {
	ret := _m.Called(ctx, user, eventType)

	if len(ret) == 0 {
		panic("no return value specified for EmitUserEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.User, string) error); ok {
		r0 = rf(ctx, user, eventType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventEmitter creates a new instance of EventEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventEmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventEmitter {
	mock := &EventEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
