// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/jideobs/nebularcore/modules/auth/models"

	time "time"

	uuid "github.com/google/uuid"
)

// PermissionRepository is an autogenerated mock type for the PermissionRepository type
type PermissionRepository struct {
	mock.Mock
}

// AddUserToGroup provides a mock function with given fields: ctx, userID, groupID, expiresAt
func (_m *PermissionRepository) AddUserToGroup(ctx context.Context, userID string, groupID string, expiresAt *time.Time) error {
	ret := _m.Called(ctx, userID, groupID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *time.Time) error); ok {
		r0 = rf(ctx, userID, groupID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssignPermissionToGroup provides a mock function with given fields: ctx, groupID, permissionID, expiresAt
func (_m *PermissionRepository) AssignPermissionToGroup(ctx context.Context, groupID string, permissionID string, expiresAt *time.Time) error {
	ret := _m.Called(ctx, groupID, permissionID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermissionToGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *time.Time) error); ok {
		r0 = rf(ctx, groupID, permissionID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssignPermissionToRole provides a mock function with given fields: ctx, roleID, permissionID, grantedByID, roleName
func (_m *PermissionRepository) AssignPermissionToRole(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID, grantedByID uuid.UUID, roleName string) error {
	ret := _m.Called(ctx, roleID, permissionID, grantedByID, roleName)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermissionToRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, roleID, permissionID, grantedByID, roleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssignPermissionToUser provides a mock function with given fields: ctx, userID, permissionID, grantedBy
func (_m *PermissionRepository) AssignPermissionToUser(ctx context.Context, userID uuid.UUID, permissionID uuid.UUID, grantedBy uuid.UUID) error {
	ret := _m.Called(ctx, userID, permissionID, grantedBy)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermissionToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, permissionID, grantedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateGroup provides a mock function with given fields: ctx, group
func (_m *PermissionRepository) CreateGroup(ctx context.Context, group *models.PermissionGroup) (*models.PermissionGroup, error) {
	ret := _m.Called(ctx, group)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 *models.PermissionGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PermissionGroup) (*models.PermissionGroup, error)); ok {
		return rf(ctx, group)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.PermissionGroup) *models.PermissionGroup); ok {
		r0 = rf(ctx, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PermissionGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.PermissionGroup) error); ok {
		r1 = rf(ctx, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePermission provides a mock function with given fields: ctx, permission
func (_m *PermissionRepository) CreatePermission(ctx context.Context, permission *models.Permission) (*models.Permission, error) {
	ret := _m.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermission")
	}

	var r0 *models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Permission) (*models.Permission, error)); ok {
		return rf(ctx, permission)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Permission) *models.Permission); ok {
		r0 = rf(ctx, permission)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Permission) error); ok {
		r1 = rf(ctx, permission)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroupPermissions provides a mock function with given fields: ctx, groupID
func (_m *PermissionRepository) GetGroupPermissions(ctx context.Context, groupID string) ([]*models.Permission, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupPermissions")
	}

	var r0 []*models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.Permission, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.Permission); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRolePermissions provides a mock function with given fields: ctx, roleID
func (_m *PermissionRepository) GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]*models.Permission, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetRolePermissions")
	}

	var r0 []*models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Permission, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Permission); ok {
		r0 = rf(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserGroups provides a mock function with given fields: ctx, userID
func (_m *PermissionRepository) GetUserGroups(ctx context.Context, userID string) ([]*models.UserGroup, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGroups")
	}

	var r0 []*models.UserGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.UserGroup, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.UserGroup); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.UserGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPermissions provides a mock function with given fields: ctx, userID
func (_m *PermissionRepository) GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]*models.Permission, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 []*models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Permission, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Permission); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasPermission provides a mock function with given fields: ctx, userID, resource, action
func (_m *PermissionRepository) HasPermission(ctx context.Context, userID uuid.UUID, resource string, action string) (bool, error) {
	ret := _m.Called(ctx, userID, resource, action)

	if len(ret) == 0 {
		panic("no return value specified for HasPermission")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (bool, error)); ok {
		return rf(ctx, userID, resource, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) bool); ok {
		r0 = rf(ctx, userID, resource, action)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, userID, resource, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokePermissionToRole provides a mock function with given fields: ctx, roleID, permissionID, roleName
func (_m *PermissionRepository) RevokePermissionToRole(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID, roleName string) error {
	ret := _m.Called(ctx, roleID, permissionID, roleName)

	if len(ret) == 0 {
		panic("no return value specified for RevokePermissionToRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, roleID, permissionID, roleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokePermissionToUser provides a mock function with given fields: ctx, userID, permissionID
func (_m *PermissionRepository) RevokePermissionToUser(ctx context.Context, userID uuid.UUID, permissionID uuid.UUID) error {
	ret := _m.Called(ctx, userID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokePermissionToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, permissionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPermissionRepository creates a new instance of PermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionRepository {
	mock := &PermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
