// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	models "gitlab.com/jideobs/nebularcore/modules/auth/models"

	paginate "github.com/morkid/paginate"

	responses "gitlab.com/jideobs/nebularcore/modules/auth/models/responses"

	uuid "github.com/google/uuid"
)

// ResourceRepository is an autogenerated mock type for the ResourceRepository type
type ResourceRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, resource
func (_m *ResourceRepository) Create(ctx context.Context, resource *models.Resource) error {
	ret := _m.Called(ctx, resource)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Resource) error); ok {
		r0 = rf(ctx, resource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ResourceRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Filter provides a mock function with given fields: ctx, filter
func (_m *ResourceRepository) Filter(ctx context.Context, filter string) ([]responses.FilterResourcePayload, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 []responses.FilterResourcePayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]responses.FilterResourcePayload, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []responses.FilterResourcePayload); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responses.FilterResourcePayload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ResourceRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.Resource, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Resource, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Resource); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByModule provides a mock function with given fields: ctx, moduleName
func (_m *ResourceRepository) FindByModule(ctx context.Context, moduleName string) ([]*models.Resource, error) {
	ret := _m.Called(ctx, moduleName)

	if len(ret) == 0 {
		panic("no return value specified for FindByModule")
	}

	var r0 []*models.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.Resource, error)); ok {
		return rf(ctx, moduleName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.Resource); ok {
		r0 = rf(ctx, moduleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, moduleName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByResource provides a mock function with given fields: ctx, resource
func (_m *ResourceRepository) FindByResource(ctx context.Context, resource string) (*models.Resource, error) {
	ret := _m.Called(ctx, resource)

	if len(ret) == 0 {
		panic("no return value specified for FindByResource")
	}

	var r0 *models.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Resource, error)); ok {
		return rf(ctx, resource)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Resource); ok {
		r0 = rf(ctx, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, resource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, r
func (_m *ResourceRepository) List(ctx context.Context, r *http.Request) paginate.Page {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 paginate.Page
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) paginate.Page); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(paginate.Page)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, id, resource
func (_m *ResourceRepository) Update(ctx context.Context, id uuid.UUID, resource *models.Resource) error {
	ret := _m.Called(ctx, id, resource)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.Resource) error); ok {
		r0 = rf(ctx, id, resource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewResourceRepository creates a new instance of ResourceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceRepository {
	mock := &ResourceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
