// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pkg "gitlab.com/jideobs/nebularcore/modules/auth/pkg"
)

// GoogleSignin is an autogenerated mock type for the GoogleSignin type
type GoogleSignin struct {
	mock.Mock
}

// Exchange provides a mock function with given fields: ctx, code
func (_m *GoogleSignin) Exchange(ctx context.Context, code string) (*pkg.GoogleUser, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *pkg.GoogleUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*pkg.GoogleUser, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *pkg.GoogleUser); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.GoogleUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuthURL provides a mock function with given fields: state
func (_m *GoogleSignin) GetAuthURL(state string) string {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// VerifyGoogleIDToken provides a mock function with given fields: ctx, tokenString
func (_m *GoogleSignin) VerifyGoogleIDToken(ctx context.Context, tokenString string) (*pkg.GoogleUser, error) {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for VerifyGoogleIDToken")
	}

	var r0 *pkg.GoogleUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*pkg.GoogleUser, error)); ok {
		return rf(ctx, tokenString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *pkg.GoogleUser); ok {
		r0 = rf(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.GoogleUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGoogleSignin creates a new instance of GoogleSignin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleSignin(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleSignin {
	mock := &GoogleSignin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
