// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "gitlab.com/jideobs/nebularcore/modules/auth/models"

	types "gitlab.com/jideobs/nebularcore/modules/auth/types"
)

// SocialAccountRepository is an autogenerated mock type for the SocialAccountRepository type
type SocialAccountRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, data
func (_m *SocialAccountRepository) Create(ctx context.Context, data *models.SocialAccount) (*models.SocialAccount, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.SocialAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.SocialAccount) (*models.SocialAccount, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.SocialAccount) *models.SocialAccount); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SocialAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.SocialAccount) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByUserID provides a mock function with given fields: ctx, userID
func (_m *SocialAccountRepository) DeleteByUserID(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByProvider provides a mock function with given fields: ctx, provider, providerUserID
func (_m *SocialAccountRepository) FindByProvider(ctx context.Context, provider types.AuthProvider, providerUserID string) (*models.SocialAccount, error) {
	ret := _m.Called(ctx, provider, providerUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindByProvider")
	}

	var r0 *models.SocialAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AuthProvider, string) (*models.SocialAccount, error)); ok {
		return rf(ctx, provider, providerUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AuthProvider, string) *models.SocialAccount); ok {
		r0 = rf(ctx, provider, providerUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SocialAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AuthProvider, string) error); ok {
		r1 = rf(ctx, provider, providerUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *SocialAccountRepository) FindByUserID(ctx context.Context, userID string) (*models.SocialAccount, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 *models.SocialAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.SocialAccount, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.SocialAccount); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SocialAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSocialAccountRepository creates a new instance of SocialAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSocialAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SocialAccountRepository {
	mock := &SocialAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
