// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	interfaces "gitlab.com/jideobs/nebularcore/modules/auth/interfaces"
)

// SocialAccount is an autogenerated mock type for the SocialAccount type
type SocialAccount struct {
	mock.Mock
}

// GetID provides a mock function with no fields
func (_m *SocialAccount) GetID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetMetadata provides a mock function with no fields
func (_m *SocialAccount) GetMetadata() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// GetProvider provides a mock function with no fields
func (_m *SocialAccount) GetProvider() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProvider")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetProviderUserID provides a mock function with no fields
func (_m *SocialAccount) GetProviderUserID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProviderUserID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUser provides a mock function with no fields
func (_m *SocialAccount) GetUser() interfaces.User {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 interfaces.User
	if rf, ok := ret.Get(0).(func() interfaces.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.User)
		}
	}

	return r0
}

// GetUserID provides a mock function with no fields
func (_m *SocialAccount) GetUserID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewSocialAccount creates a new instance of SocialAccount. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSocialAccount(t interface {
	mock.TestingT
	Cleanup(func())
}) *SocialAccount {
	mock := &SocialAccount{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
