// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	types "github.com/volvlabs/nebularcore/tools/types"

	uuid "github.com/google/uuid"
)

// User is an autogenerated mock type for the User type
type User struct {
	mock.Mock
}

// GetEmail provides a mock function with no fields
func (_m *User) GetEmail() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEmail")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetEmailVerified provides a mock function with no fields
func (_m *User) GetEmailVerified() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEmailVerified")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetEmailVerifiedAt provides a mock function with no fields
func (_m *User) GetEmailVerifiedAt() *types.DateTime {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEmailVerifiedAt")
	}

	var r0 *types.DateTime
	if rf, ok := ret.Get(0).(func() *types.DateTime); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.DateTime)
		}
	}

	return r0
}

// GetID provides a mock function with no fields
func (_m *User) GetID() uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// GetLastLoginAt provides a mock function with no fields
func (_m *User) GetLastLoginAt() *time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastLoginAt")
	}

	var r0 *time.Time
	if rf, ok := ret.Get(0).(func() *time.Time); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	return r0
}

// GetMetadata provides a mock function with no fields
func (_m *User) GetMetadata() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// GetPasswordHash provides a mock function with no fields
func (_m *User) GetPasswordHash() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPasswordHash")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPasswordResetAt provides a mock function with no fields
func (_m *User) GetPasswordResetAt() *time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPasswordResetAt")
	}

	var r0 *time.Time
	if rf, ok := ret.Get(0).(func() *time.Time); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	return r0
}

// GetPasswordResetToken provides a mock function with no fields
func (_m *User) GetPasswordResetToken() *string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPasswordResetToken")
	}

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// GetPhoneNumber provides a mock function with no fields
func (_m *User) GetPhoneNumber() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPhoneNumber")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetRole provides a mock function with no fields
func (_m *User) GetRole() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUsername provides a mock function with no fields
func (_m *User) GetUsername() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUsername")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsActive provides a mock function with no fields
func (_m *User) IsActive() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsActive")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SetPassword provides a mock function with given fields: password
func (_m *User) SetPassword(password string) {
	_m.Called(password)
}

// SetPasswordResetAt provides a mock function with given fields: at
func (_m *User) SetPasswordResetAt(at *time.Time) {
	_m.Called(at)
}

// SetPasswordResetToken provides a mock function with given fields: token
func (_m *User) SetPasswordResetToken(token *string) {
	_m.Called(token)
}

// NewUser creates a new instance of User. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *User {
	mock := &User{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
