// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	gin "github.com/gin-gonic/gin"
	gorm "gorm.io/gorm"

	migration_runner "gitlab.com/jideobs/nebularcore/core/migration_runner"

	mock "github.com/stretchr/testify/mock"

	module "gitlab.com/jideobs/nebularcore/core/module"
)

// Module is an autogenerated mock type for the Module type
type Module struct {
	mock.Mock
}

// Configure provides a mock function with given fields: config
func (_m *Module) Configure(config interface{}) error {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Dependencies provides a mock function with no fields
func (_m *Module) Dependencies() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dependencies")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetMigrationSources provides a mock function with given fields: projectRoot
func (_m *Module) GetMigrationSources(projectRoot string) []migration_runner.Source {
	ret := _m.Called(projectRoot)

	if len(ret) == 0 {
		panic("no return value specified for GetMigrationSources")
	}

	var r0 []migration_runner.Source
	if rf, ok := ret.Get(0).(func(string) []migration_runner.Source); ok {
		r0 = rf(projectRoot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]migration_runner.Source)
		}
	}

	return r0
}

// Initialize provides a mock function with given fields: ctx, db, router
func (_m *Module) Initialize(ctx context.Context, db *gorm.DB, router *gin.Engine) error {
	ret := _m.Called(ctx, db, router)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *gin.Engine) error); ok {
		r0 = rf(ctx, db, router)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MigrationsDir provides a mock function with no fields
func (_m *Module) MigrationsDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MigrationsDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Name provides a mock function with no fields
func (_m *Module) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Namespace provides a mock function with no fields
func (_m *Module) Namespace() module.ModuleNamespace {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Namespace")
	}

	var r0 module.ModuleNamespace
	if rf, ok := ret.Get(0).(func() module.ModuleNamespace); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(module.ModuleNamespace)
	}

	return r0
}

// NewConfig provides a mock function with no fields
func (_m *Module) NewConfig() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewConfig")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// ProvidesMigrations provides a mock function with no fields
func (_m *Module) ProvidesMigrations() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProvidesMigrations")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Shutdown provides a mock function with given fields: ctx
func (_m *Module) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Version provides a mock function with no fields
func (_m *Module) Version() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewModule creates a new instance of Module. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *Module {
	mock := &Module{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
