// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	io "io"

	source "github.com/golang-migrate/migrate/v4/source"
	mock "github.com/stretchr/testify/mock"
)

// Driver is an autogenerated mock type for the Driver type
type Driver struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *Driver) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// First provides a mock function with no fields
func (_m *Driver) First() (uint, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for First")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Next provides a mock function with given fields: version
func (_m *Driver) Next(version uint) (uint, error) {
	ret := _m.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (uint, error)); ok {
		return rf(version)
	}
	if rf, ok := ret.Get(0).(func(uint) uint); ok {
		r0 = rf(version)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Open provides a mock function with given fields: url
func (_m *Driver) Open(url string) (source.Driver, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 source.Driver
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (source.Driver, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) source.Driver); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(source.Driver)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Prev provides a mock function with given fields: version
func (_m *Driver) Prev(version uint) (uint, error) {
	ret := _m.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for Prev")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (uint, error)); ok {
		return rf(version)
	}
	if rf, ok := ret.Get(0).(func(uint) uint); ok {
		r0 = rf(version)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadDown provides a mock function with given fields: version
func (_m *Driver) ReadDown(version uint) (io.ReadCloser, string, error) {
	ret := _m.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for ReadDown")
	}

	var r0 io.ReadCloser
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(uint) (io.ReadCloser, string, error)); ok {
		return rf(version)
	}
	if rf, ok := ret.Get(0).(func(uint) io.ReadCloser); ok {
		r0 = rf(version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) string); ok {
		r1 = rf(version)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(uint) error); ok {
		r2 = rf(version)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ReadUp provides a mock function with given fields: version
func (_m *Driver) ReadUp(version uint) (io.ReadCloser, string, error) {
	ret := _m.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for ReadUp")
	}

	var r0 io.ReadCloser
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(uint) (io.ReadCloser, string, error)); ok {
		return rf(version)
	}
	if rf, ok := ret.Get(0).(func(uint) io.ReadCloser); ok {
		r0 = rf(version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) string); ok {
		r1 = rf(version)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(uint) error); ok {
		r2 = rf(version)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewDriver creates a new instance of Driver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *Driver {
	mock := &Driver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
