// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package types

import (
	"errors"
	"fmt"
)

const (
	// BackendKafka is a Backend of type kafka.
	BackendKafka Backend = "kafka"
	// BackendGoChannels is a Backend of type goChannels.
	BackendGoChannels Backend = "goChannels"
)

var ErrInvalidBackend = errors.New("not a valid Backend")

// String implements the Stringer interface.
func (x Backend) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Backend) IsValid() bool {
	_, err := ParseBackend(string(x))
	return err == nil
}

var _BackendValue = map[string]Backend{
	"kafka":      BackendKafka,
	"goChannels": BackendGoChannels,
}

// ParseBackend attempts to convert a string to a Backend.
func ParseBackend(name string) (Backend, error) {
	if x, ok := _BackendValue[name]; ok {
		return x, nil
	}
	return Backend(""), fmt.Errorf("%s is %w", name, ErrInvalidBackend)
}

// MarshalText implements the text marshaller method.
func (x Backend) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Backend) UnmarshalText(text []byte) error {
	tmp, err := ParseBackend(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
