// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/jideobs/nebularcore/modules/auth/models"

	requests "gitlab.com/jideobs/nebularcore/modules/auth/models/requests"

	uuid "github.com/google/uuid"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// AssignRole provides a mock function with given fields: ctx, userID, roleID, roleName
func (_m *Manager) AssignRole(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, roleName string) error {
	ret := _m.Called(ctx, userID, roleID, roleName)

	if len(ret) == 0 {
		panic("no return value specified for AssignRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, roleID, roleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePermission provides a mock function with given fields: ctx, payload
func (_m *Manager) CreatePermission(ctx context.Context, payload *requests.CreatePermissionPayload) (*models.Permission, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermission")
	}

	var r0 *models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.CreatePermissionPayload) (*models.Permission, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *requests.CreatePermissionPayload) *models.Permission); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *requests.CreatePermissionPayload) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRole provides a mock function with given fields: ctx, payload
func (_m *Manager) CreateRole(ctx context.Context, payload *requests.CreateRolePayload) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.CreateRolePayload) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRolePermissions provides a mock function with given fields: ctx, roleID
func (_m *Manager) GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]*models.Permission, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetRolePermissions")
	}

	var r0 []*models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Permission, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Permission); ok {
		r0 = rf(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserDirectPermissions provides a mock function with given fields: ctx, userID
func (_m *Manager) GetUserDirectPermissions(ctx context.Context, userID uuid.UUID) ([]*models.Permission, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDirectPermissions")
	}

	var r0 []*models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Permission, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Permission); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRoles provides a mock function with given fields: ctx, userID
func (_m *Manager) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]*models.Role, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoles")
	}

	var r0 []*models.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Role, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Role); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GrantRolePermission provides a mock function with given fields: ctx, roleID, permissionID, grantedByID, roleName
func (_m *Manager) GrantRolePermission(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID, grantedByID uuid.UUID, roleName string) error {
	ret := _m.Called(ctx, roleID, permissionID, grantedByID, roleName)

	if len(ret) == 0 {
		panic("no return value specified for GrantRolePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, roleID, permissionID, grantedByID, roleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GrantUserPermission provides a mock function with given fields: ctx, userID, permissionID, grantedByID
func (_m *Manager) GrantUserPermission(ctx context.Context, userID uuid.UUID, permissionID uuid.UUID, grantedByID uuid.UUID) error {
	ret := _m.Called(ctx, userID, permissionID, grantedByID)

	if len(ret) == 0 {
		panic("no return value specified for GrantUserPermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, permissionID, grantedByID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasPermission provides a mock function with given fields: ctx, userID, resource, action
func (_m *Manager) HasPermission(ctx context.Context, userID uuid.UUID, resource string, action string) (bool, error) {
	ret := _m.Called(ctx, userID, resource, action)

	if len(ret) == 0 {
		panic("no return value specified for HasPermission")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (bool, error)); ok {
		return rf(ctx, userID, resource, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) bool); ok {
		r0 = rf(ctx, userID, resource, action)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, userID, resource, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasRole provides a mock function with given fields: ctx, userID, roleName
func (_m *Manager) HasRole(ctx context.Context, userID uuid.UUID, roleName string) (bool, error) {
	ret := _m.Called(ctx, userID, roleName)

	if len(ret) == 0 {
		panic("no return value specified for HasRole")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return rf(ctx, userID, roleName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = rf(ctx, userID, roleName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, roleName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeRolePermission provides a mock function with given fields: ctx, roleID, permissionID, roleName
func (_m *Manager) RevokeRolePermission(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID, roleName string) error {
	ret := _m.Called(ctx, roleID, permissionID, roleName)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRolePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, roleID, permissionID, roleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeUserPermission provides a mock function with given fields: ctx, userID, permissionID
func (_m *Manager) RevokeUserPermission(ctx context.Context, userID uuid.UUID, permissionID uuid.UUID) error {
	ret := _m.Called(ctx, userID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeUserPermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, permissionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnassignRole provides a mock function with given fields: ctx, userID, roleID, roleName
func (_m *Manager) UnassignRole(ctx context.Context, userID uuid.UUID, roleID uuid.UUID, roleName string) error {
	ret := _m.Called(ctx, userID, roleID, roleName)

	if len(ret) == 0 {
		panic("no return value specified for UnassignRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, roleID, roleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
